### ISSUE TITLE
RuntimeError: tf.metrics.accuracy is not supported when eager execution is enabled

### ISSUE THREAD

**Issue by tongcu** [tensorflow/probability#329] opened 2019-03-15 07:45 UTC
as running the following sample code :logistic_regression.py	s/tf.name_scope/tf.compat.v1.name_scope/ 
it always reports error like
/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
W0315 15:34:39.527458 140735853056896 toy_tfp.py:154] Warning: deleting old log directory at /tmp/logistic_regression/
2019-03-15 15:34:39.529648: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "toy_tfp.py", line 219, in <module>
    tf.compat.v1.app.run()
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/anaconda2/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/anaconda2/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "toy_tfp.py", line 185, in main
    labels=labels, predictions=predictions)
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/metrics_impl.py", line 447, in accuracy
    raise RuntimeError('tf.metrics.accuracy is not supported when eager '
RuntimeError: tf.metrics.accuracy is not supported when eager execution is enabled.

**Comment by jvdillon** [comment] 2019-03-17 15:08
This looks like a problem with "core TensorFlow" not "TensorFlow Probability". Please raise the issue there,
https://github.com/tensorflow/tensorflow/issues

**Comment by jvdillon** [comment] 2019-03-17 15:10
My mistake. I believe the issue is that our examples are not yet migrated to TF2.
**All TFP non-example code is TF2 ready.**

**Comment by srvasude** [comment] 2020-02-08 01:54
Closing this issue in favor of tracking this in #416

**Closed by srvasude** 2020-02-08 01:54 UTC
