### ISSUE TITLE
tfp.sts future forecasting with external (holiday) regressor

### ISSUE THREAD

**Issue by abc-8** [tensorflow/probability#343] opened 2019-03-29 14:42 UTC
Referring to electricity demand in the example notebook:

https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Structural_Time_Series_Modeling_Case_Studies_Atmospheric_CO2_and_Electricity_Demand.ipynb

given the future temperature (e.g. 2014-02-27 00:00:00 ->   2014-02-28 00:00:00), how can I 
call `tfp.sts.forecast` method?

**Comment by davmre** [comment] 2019-04-01 17:37
Great question. It's a little confusing to talk about because of a
distinction we didn't make very clear in the post: of course a model that
depends on external covariates can't properly produce 'forecasts' of the
future (because it requires we know the values of the covariates!) -- but
it can be used for 'nowcasting' (estimating a hard-to-observe or
infrequently-observed quantity given an easily-observed quantity, e.g., flu
occurrence given web search trends), or of course you can go deeper
and plug in forecasts of the covariates, though properly handling the
uncertainty in these forecasts can gets tricky.

Concretely: `tfp.sts.forecast` extends each model component over additional
steps, including the LinearRegression component, so it needs a model that
includes the 'future' covariates as part of the LinearRegression design
matrix. That is, the design matrix should concatenate the temperature for
both the training and 'forecast' periods:

```
# training_temperature.shape == [num_train_steps, 1]
# forecast_temperature.shape == [num_forecast_steps, 1]
temperature_effect = tfp.sts.LinearRegression(
  design_matrix = tf.concat([training_temperature, forecast_temperature],
axis=0))
```

This is actually what the example notebook already does, implicitly: it
just defines 'temperature' that covers both the training and forecast time
periods.

Hope this helps!

Dave

**Comment by abc-8** [comment] 2019-04-08 14:29
@davmre Thanks,

what I meant is how you continue forecasting the future after (production), say you have a weather service that feeds your production model with tomorrow's hourly weather, so you always have to append tomorrow weather to forecast tomorrow's demand.

I found a solution for this by hacking. that is, mutating  `LinearRegression`'s design_matrix before calling `tfp.sts.forecast()`, and its working like a charm:

```python
# in this example, consider the dataset contains demand data till today
tomorrow_weather = service.weather_future_forecast('tomorrow') # next 24 hours
weather_matrix = tf.concat([ temperature_effect._design_matrix.to_dense(), tomorrow_weather], axis=0)
temperature_effect._design_matrix = tf.linalg.LinearOperatorFullMatrix(
            weather_matrix,
            name='design_matrix_linop')
# continue by calling tfp.sts.forecast with `num_steps_forecast=24`
```

and that lead us to another question:

**is this the right way to forecast ? or do I need to retrain the model everytime I change `LinearRegression` design_matrix ?** I don't have extensive knowledge about variational inference that's why I'm wondering if this is OK.

Thanks,

**Comment by davmre** [comment] 2019-04-08 18:34
Mutating private members is probably not an engineering best practice, but
mathematically what you're doing is fine. Fitting the model (whether with
VI or HMC) gives you a set of posterior samples for the parameters of the
model given your training inputs; for LinearRegression, those parameters
are the regression weights. As long as your new design matrix has the same
set of features, there's no reason to retrain new weights unless you want
to incorporate new training data.

From a coding standpoint, you could avoid mutating private state by just
creating a new STS model object (including the LinearRegression and
whatever other components you're using) with the new design matrix. STS
models are stateless, so once you've gotten posterior samples of the
parameters, there's nothing special about the original model object; a new
model with the same structure (thus same set of parameters) but a different
design matrix will work just as well.

Dave

**Comment by mjablonski-hive** [comment] 2019-04-15 15:16
Hello. Guys I was trying to run the example on Colab and I'm getting lot's of errors (especially with Autoregressive). Did something change in API? Thanks

**Comment by axch** [comment] 2019-05-09 20:42
@abc-8, assuming your question has been answered, I'm going to go ahead and close this issue.  Please reopen (or file a new one) as needed.

**Closed by axch** 2019-05-09 20:42 UTC
