### ISSUE TITLE
Cholesky decomposition failure in VariationalGaussianProcess.__compute_posterior_predictive_params

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#650] opened 2019-11-20 13:47 UTC
Hi,

I've been porting the  VariationalGaussianProcess-related code from this notebook: 

https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb

to R.

Working with the same dataset (but different random initialization), I get  a Cholesky decomposition failure when trying to obtain predictions:

https://github.com/tensorflow/probability/blob/9399b67e74d0ba45cd3bb7fa266dca3b7afe2421/tensorflow_probability/python/distributions/variational_gaussian_process.py#L676

Would you have an idea what could be the reason? The failure seems to get more likely the better trained the network (the lower the loss), but that could be purely incidental...

I'm using the same parameter settings as the colab. One thing I notice in both places, colab and my port:

```
WARNING:tensorflow:Gradients do not exist for variables ['variational_gaussian_process_4/observation_noise_variance:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['variational_gaussian_process_4/observation_noise_variance:0'] when minimizing the loss.
```

Could this be related?

I also saw your comment @csuter here

https://github.com/tensorflow/probability/issues/448#issuecomment-555615511

The colab seems to indicate that VariationalGaussianProcess works fine with TF 2... could there be exceptions still?

Many thanks!

**Comment by csuter** [comment] 2019-11-20 19:11
Hi Sigrid, numerical issues in Cholesky decompositions are a common failure mode in GP optimizations. Are you using float64 types? float32 is more susceptible to these failures, unless you crank up the `jitter` term accordingly. You'll also need to make sure your `observation_noise_variance` is constrained to be positive (perhaps even strictly positive, by adding a small positive nonzero value to it). These are usually the first things I try when I hit Cholesky decomposition failures. Let me know if you've already tried all that and still having issues :). With VGP you can also run into issues if the inducing points collapse together, resulting in a degenerate `k(z, z')` matrix of kernel values at the inducing points. This can be mitigated, e.g., by ensuring that the inducing points are initialized "not too close" together (where "closeness" is defined by the kernel and its parameters). HTH!

**Comment by skeydan** [comment] 2019-11-21 10:06
Thank you Chris, that helps a lot!! For this example (the one from the colab) it's already sufficient to use `float64` (which I wasn't doing before) :-)

But it's good to know other things to try, as I'll be looking for some real-world dataset to apply this to :-)

Just to be sure, do I need to worry about that warning (which also appears in the colab)

```
WARNING:tensorflow:Gradients do not exist for variables ['variational_gaussian_process/observation_noise_variance:0'] when minimizing the loss.
```

Actually I probably don't need to worry (as performance is good now), but perhaps on your side it means there's something still to be done for TF 2 compatibility?

**Comment by csuter** [comment] 2019-11-21 22:07
VGP has not been "tape-safety" migrated yet (to my chagrin....it's on my plate).

This warning means that somewhere along the line, a computation based on the `observation_noise_variance` `tf.Variable` is being stored, instead of the variable itself, and the gradient signal back to the variable is being broken. Generally, the workaround is to make sure all computations that consume `observation_noise_variance`, as well as the the VGP instance creation, happen inside the scope of a `GradientTape`. Now, if you're following the regression colab, probably 1. there is a variable being created for you, in the Layer __init__/build routines (can't recall which) and 2. you don't actually have access to any gradient tape because it's owned by Keras.

Can you possibly share some of the R code you're developing (feel free to email me directly)? I may better be able to diagnose and propose a workaround.

**Comment by skeydan** [comment] 2019-11-22 07:51
Thanks Chris!  Absolutely I can paste the R code here, but right now it is really just a literal translation of

 https://colab.research.google.com/github/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_Layers_Regression.ipynb

which probably would be more convenient for you to work with?

(So, no `GradientTape` used, just Keras...)

**Comment by skeydan** [comment] 2019-11-22 18:14
Hi Chris, me again :-)

I'm now applying the same (basically, apart from shape stuff) code to a "real-world" dataset which has 6 columns (predictors). However, I have problems getting the `inducing_index_points_initializer` correct...

Let's say I set `num_inducing_points` to 7, then I thought I would pass an `7 * 6` - dimensional array there... but the error I get is

```
TypeError: Eager execution of tf.constant with unsupported shape
 (value has 42 elements, shape is (1, 7, 1) with 7 elements)
```

Would you happen to have an idea what I can do? Many thanks!

I don't understand why the expected shape would be (1,7,1) when my dataset is 6-dimensional?

**Comment by JimAva** [comment] 2019-11-30 02:44
I have run into the same issue with **WARNING:tensorflow:Gradients do not exist for variables ['variational_gaussian_process**.  I've tried the nightly builds to no avail.  Any update?

**Comment by srvasude** [comment] 2020-02-14 10:32
I am going to close this as VGP should be updated for TF2 / tape-safety. Feel free to reopen if this is still an issue.

**Closed by srvasude** 2020-02-14 10:32 UTC
