### ISSUE TITLE
ed2 random variable sample shape tensor can be accidentally defined in a different tensorflow graph

### ISSUE THREAD

**Issue by jcozar87** [tensorflow/probability#287] opened 2019-02-07 10:49 UTC
I am using `tensorflow` graph contexts to define edward2 Random Variables. For example:

```python
import numpy as np
import tensorflow as tf
from tensorflow_probability import edward2 as ed

tf_graph = tf.Graph()
with tf_graph.as_default():
    w = ed.Normal(np.zeros([4,2], np.float32), 1., sample_shape=2, name='w')
    x = ed.Normal(np.zeros([2,4], np.float32), 1., sample_shape=2, name='x')
    y = ed.Normal(tf.constant(10.) + tf.matmul(x, w), 0., name='y')
```

I have seen that if I try to get the tensor related to the Random Variable **y** (`y.value`) out of the `tf_graph.as_default()` scope, it raises an Exception:

```
ValueError: Tensor("y/Identity:0", shape=(2, 2, 2), dtype=float32) must be from the same graph as Tensor("sample_shape_tensor/Const:0", shape=(0,), dtype=int32).
```

Exploring the source code in `tensorflow_probability/python/edward2/random_variable.py`, I have seen that `value` property  returns `self._value = self.distribution.sample(self.sample_shape_tensor())` if `self._value is None`.

Calling to `self.sample_shape_tensor()` function calls to `tf.convert_to_tensor(self.sample_shape.as_list(), dtype=tf.int32)` function, if `not isinstance(self._sample_shape, tf.Tensor)`. This implies that the _sample shape tensor_ is created in the tensorflow global graph, which is a different graph from where the random variable `y` was defined.

I open this issue because I do not know if this behaviour is on purpose, and the _sample shape tensor_ **must** be created just when the `.value` property is called, and cannot be created in the `__init__` function of the Random Variable. If it is the case, would you mind to explain me briefly why this is required? (I have studied the `random_variable.py` source code, but I do not understand it). Otherwise, I can create a pull request to change this behaviour if you want.

**Comment by davmre** [comment] 2019-02-08 05:15
Hi Javier! Thanks for the report. I think the broader effect you're running into is that Edward2 random variables instantiate their sampled values lazily, on first access, instead of on construction. (the issue isn't specific to `self.sample_shape_tensor()`; even if it was created earlier on you would still get a similar error for the `distribution.sample()`call).

There are at least some reasons to do it this way, e.g., it helps ensure that the value is only sampled for variables where it's actually needed, and not if (say) the model is running in an interception context that will override the value. It's likely possible to work around this, but it would require some thought and possibly limit the semantics of future interceptors, which is undesirable insofar as Edward2 is still an open-ended research platform.

You can always work around this by forcibly instantiating the value inside the graph scope:
```
y = ed.Normal(tf.constant(10.) + tf.matmul(x, w), 0., name='y')
_ = y.value
```
though that's obviously not ideal. Have you considered whether you really need to use multiple graphs? It's relatively rare to use anything other than the default graph in modern idiomatic TensorFlow code (I don't think we have multiple graphs in any TFP examples), partly due to errors like the one you're seeing. :-)  What benefit are you getting from using a separate graph context? We might be able to suggest an alternative approach.

**Comment by jcozar87** [comment] 2019-02-08 13:33
Hi Dave,

thank you for your detailed response! I understand now the reasons for that lazy instantiation in the case of `distribution.value` and `sample_shape_tensor`. 

My motivation for using TF graph contexts is that, as it happens in the [PCA](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Probabilistic_PCA.ipynb) example, you call the model function multiple times during the notebook (e.g.: to sample training data, to create the objective function, ...). Each time this function is called, tensors are registered in the same (default) TF graph. I think that this could be especially inefficient when the model is huge (e.g.: a probabilistic DNN with thousands of random variables).

We think that the advantage of using TF graph contexts is that the tensors of the same model are registered in independent graphs, and you can easily manage each one of them separately. Should be better to use the default graph and reset it when appropriate?

Thank you in advance.

**Comment by davmre** [comment] 2019-02-12 00:36
For notebooks, I've personally found it tends to work well to write in multiple 'sections' and reset the graph at the beginning of each section. Each section contains a coherent computation done with a single graph, and components that get reused between sections (like the model definition) are defined as callables so you can easily rebuild the same ops in different graphs. In general, callables can be a nicer way of grouping related operations than TF graphs, because you can rely on Python scoping to ensure you never access values in the 'wrong' graph.

FWIW, graphs themselves will become less idiomatic as TF 2.0 becomes eager-by-default. The pattern that seems to be emerging is to write code with eager-mode semantics and decorate any expensive functions with [`@tfe.function`](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf/contrib/eager/function), which recovers most of the benefits of graph mode by tracing that function to implicitly create a mini-graph that can be reused cheaply. There are still some warts with this approach, and graphs definitely aren't going away anytime soon, but our experience has been that eager-first code is often clearer and easier to reason about than code that makes heavy use of graph features (placeholders, global variables, etc). Hopefully we'll publish more examples in this style in the weeks/months to come.

**Comment by srvasude** [comment] 2020-02-07 05:05
Closing this as Edward2 has moved to https://github.com/google/edward2. I believe this issue is also not so much a worry anymore given TF2 and tf.function adoption.

**Closed by srvasude** 2020-02-07 05:05 UTC
