### ISSUE TITLE
TruncatedNormal returns inf when mean is far from the bounds

### ISSUE THREAD

**Issue by hardianlawi** [tensorflow/probability#1214] opened 2021-01-08 16:24 UTC
Hi,

Seems like `TruncatedNormal` isn't stable when the mean is too far from the bounds. I assume the denominator in the implementation becomes zero and so the division returns inf.

```
import tensorflow_probability as tfp
tfp.distributions.TruncatedNormal(-1.0, 1.0, 14.91, 20.06).prob(17.0)  # inf
```

I'm currently using `tensorflow-probability== 0.12.1`. Using truncnorm from scipy.stats returns a number close to zero which is expected.

**Comment by thisisandreeeee** [comment] 2021-01-19 05:35
I am noticing this issue as well. Is this expected behaviour?

**Comment by davmre** [comment] 2021-01-19 22:51
Likely this is underflow because TensorFlow uses float32 by default. If I explicitly define the distribution with float64 parameters, so that it does calculations in float64:

```python
args = [tf.cast(x, tf.float64) for x in (-1.0, 1.0, 14.91, 20.06)]
tfp.distributions.TruncatedNormal(*args).prob(17.0) 
```

then it does return a finite answer (`6.512243960188414e-15`).

I'm going to close this issue on the assumption that this solves your direct problem (feel free to reopen if it doesn't), though we acknowledge the larger issue that precision gotchas like this can be annoying and sometimes subtle.

**Closed by davmre** 2021-01-19 22:51 UTC
