### ISSUE TITLE
Error when importing tensorflow_probability

### ISSUE THREAD

**Issue by ImranRolo** [tensorflow/probability#403] opened 2019-05-11 16:32 UTC
My version is Tensorflow2.0.

When I try to install tfp I get the following error:

`import tensorflow_probability as tfp`

```
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-15-41494c8c96ff> in <module>
----> 1 import tensorflow_probability as tfp


~/.local/lib/python3.7/site-packages/tensorflow_probability/__init__.py in <module>
     73 
     74 # from tensorflow_probability.google import staging  # DisableOnExport
---> 75 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     76 from tensorflow_probability.python.version import __version__
     77 # pylint: enable=g-import-not-at-top

~/.local/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py in <module>
     19 from __future__ import print_function
     20 
---> 21 from tensorflow_probability.python import bijectors
     22 from tensorflow_probability.python import distributions
     23 from tensorflow_probability.python import edward2

~/.local/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/__init__.py in <module>
     27 from tensorflow_probability.python.bijectors.batch_normalization import BatchNormalization
     28 from tensorflow_probability.python.bijectors.bijector import Bijector
---> 29 from tensorflow_probability.python.bijectors.bijector import ConditionalBijector
     30 from tensorflow_probability.python.bijectors.blockwise import Blockwise
     31 from tensorflow_probability.python.bijectors.chain import Chain

ImportError: cannot import name 'ConditionalBijector' from 'tensorflow_probability.python.bijectors.bijector' (/home/me/.local/lib/python3.7/site-packages/tensorflow_probability/python/bijectors/bijector.py)`
```

**Comment by csuter** [comment] 2019-05-16 18:40
can you paste the output of `pip list`? i suspect something is fishy with the versions of installed packages.

**Comment by d5lewis** [comment] 2019-06-18 14:57
pip3 list
Package                 Version             
----------------------- --------------------
absl-py                 0.7.1               
alpha-vantage           2.1.0               
apturl                  0.5.2               
asn1crypto              0.24.0              
astor                   0.8.0               
awscli                  1.16.180            
bleach                  3.1.0               
blinker                 1.4                 
botocore                1.12.170            
Brlapi                  0.6.7               
cached-property         1.5.1               
certifi                 2018.8.24           
chardet                 3.0.4               
Click                   7.0                 
cloudpickle             1.1.1               
colorama                0.3.9               
command-not-found       0.3                 
cryptography            2.3                 
cupshelpers             1.0                 
cycler                  0.10.0              
decorator               4.3.0               
defer                   1.0.6               
defusedxml              0.5.0               
distro                  1.3.0               
distro-info             0.21ubuntu2         
docker                  3.4.1               
docker-compose          1.21.0              
docker-pycreds          0.3.0               
dockerpty               0.4.1               
docopt                  0.6.2               
docutils                0.14                
entrypoints             0.3                 
Flask                   1.0.3               
gast                    0.2.2               
gevent                  1.4.0               
google-pasta            0.1.7               
greenlet                0.4.15              
grpcio                  1.21.1              
h5py                    2.9.0               
html5lib                1.0.1               
httplib2                0.11.3              
idna                    2.6                 
inflection              0.3.1               
ipykernel               4.9.0               
ipython                 5.8.0               
ipython-genutils        0.2.0               
ipywidgets              6.0.0               
itsdangerous            1.1.0               
Jinja2                  2.10                
jmespath                0.9.4               
joblib                  0.13.2              
jsonschema              2.6.0               
jupyter-client          5.2.3               
jupyter-console         5.2.0               
jupyter-core            4.4.0               
Keras-Applications      1.0.8               
Keras-Preprocessing     1.1.0               
keyring                 17.1.1              
keyrings.alt            3.1.1               
kiwisolver              1.1.0               
language-selector       0.1                 
launchpadlib            1.10.6              
lazr.restfulclient      0.14.2              
lazr.uri                1.0.3               
louis                   3.8.0               
macaroonbakery          1.2.1               
Markdown                3.1.1               
MarkupSafe              1.1.0               
matplotlib              3.1.0               
mistune                 0.8.4               
more-itertools          5.0.0               
nbconvert               5.4.0               
nbformat                4.4.0               
ndg-httpsclient         0.5.1               
netifaces               0.10.4              
notebook                5.7.4               
numpy                   1.16.4              
oauthlib                2.1.0               
olefile                 0.46                
pandas                  0.24.2              
pandocfilters           1.4.2               
pexpect                 4.6.0               
pickleshare             0.7.5               
Pillow                  5.4.1               
pip                     18.1                
prometheus-client       0.5.0               
prompt-toolkit          1.0.15              
protobuf                3.6.1               
pyasn1                  0.4.5               
pycairo                 1.16.2              
pycrypto                2.6.1               
pycups                  1.9.73              
Pygments                2.3.1               
PyGObject               3.32.0              
PyJWT                   1.7.0               
pymacaroons             0.13.0              
PyNaCl                  1.3.0               
pyOpenSSL               19.0.0              
pyparsing               2.4.0               
pyRFC3339               1.1                 
python-apt              1.8.4               
python-dateutil         2.7.3               
python-debian           0.1.34              
pytz                    2018.9              
pyxdg                   0.25                
PyYAML                  3.13                
pyzmq                   17.1.2              
Quandl                  3.4.8               
reportlab               3.5.18              
requests                2.21.0              
requests-unixsocket     0.1.5               
rsa                     3.4.2               
s3transfer              0.2.1               
scikit-learn            0.21.2              
scipy                   1.3.0               
screen-resolution-extra 0.0.0               
seaborn                 0.9.0               
SecretStorage           2.3.1               
Send2Trash              1.5.0               
setuptools              41.0.1              
simplegeneric           0.8.1               
simplejson              3.16.0              
six                     1.12.0              
system-service          0.3                 
systemd-python          234                 
ta                      0.4.5               
tb-nightly              1.14.0a20190603     
tensorflow-gpu          2.0.0b1             
tensorflow-probability  0.6.0               
termcolor               1.1.0               
terminado               0.8.1               
testpath                0.4.2               
texttable               1.6.0               
tf-estimator-nightly    1.14.0.dev2019060501
tfp-nightly             0.8.0.dev20190617   
tornado                 5.1.1               
traitlets               4.3.2               
ubuntu-advantage-tools  19.2                
ubuntu-drivers-common   0.0.0               
ufw                     0.36                
unattended-upgrades     0.1                 
urllib3                 1.24.1              
wadllib                 1.3.3               
wcwidth                 0.1.7               
webencodings            0.5.1               
websocket-client        0.53.0              
Werkzeug                0.15.4              
wheel                   0.32.3              
wrapt                   1.11.2              
xkit                    0.0.0

**Comment by csuter** [comment] 2019-06-18 23:24
several issues there -- you have tensorflow-gpu (a stable build) alongside tf-estimator-nightly and tb-nightly (probably from a previous tf-nightly install).

there's also a tensorflow-probability (0.6.0) alongside a tfp-nightly.

you can only use stable with stable and nightly with nightly; everything else is very likely to fail, and having 2 side by side is almost sure to cause problems

**Comment by d5lewis** [comment] 2019-06-19 17:27
I removed everything, then:

`pip3 install tensorflow-gpu==2.0.0-beta1
`

Then: 
`Installing collected packages: tf-estimator-nightly, tb-nightly, tensorflow-gpu
Successfully installed tb-nightly-1.14.0a20190603 tensorflow-gpu-2.0.0b1 tf-estimator-nightly-1.14.0.dev2019060501
`
So it appears the tensorflow-gpu 2.0 depends on the nightly packages?

**Comment by csuter** [comment] 2019-06-19 17:41
Huh, seems so! (Sorry -- we're not strictly part of TF, so I don't know all the details of their package interdependencies).

We have a new TFP release pending (0.7 -- the RC0 of that release is out already) which will work with TF 2.0-beta. In the mean time, tfp-nightly *should* (mostly, if not 100%) work with 2.0-beta.

**Comment by srvasude** [comment] 2020-02-08 03:18
Closing this as I believe the issue is resolved. Also, in newer versions of tensorflow, I believe there is no separate GPU package, so you can just install `tensorflow`.

**Closed by srvasude** 2020-02-08 03:18 UTC
