### ISSUE TITLE
InternalError: Invalid loop structure in gradient computation when sampling Beta distribution inside scan

### ISSUE THREAD

**Issue by philipbecker** [tensorflow/probability#331] opened 2019-03-18 16:51 UTC
With tensorflow==1.13.1 and tfp==0.6.0.

#### Code to reproduce the bug
```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

inputs = tf.placeholder(tf.float32, (None, None, 1))
targets = tf.placeholder(tf.float32, (None, None, 1))

def f(acc, elems):
    alpha = tf.layers.dense(elems, 1, activation=tf.nn.softplus)
    beta = tf.layers.dense(elems, 1, activation=tf.nn.softplus)

    beta_dist = tfd.Beta(alpha, beta)
    sample = beta_dist.sample()
    return sample

outputs = tf.scan(
    f,
    inputs,
    tf.ones_like(inputs[0])
)

predictions = tf.layers.dense(outputs, 1)
loss = tf.losses.mean_squared_error(predictions, targets)

optimizer = tf.train.GradientDescentOptimizer(1e-3)
train_op = optimizer.minimize(loss)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run([loss, train_op], feed_dict={inputs: np.random.rand(3,2,1), targets: np.random.rand(3,2,1)})
```

#### Error message
```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InternalError: Invalid loop structure: Mismatched parent frames for "scan/while/while_context": "gradients/scan/while/while_context" vs "". The node giving this error: {{node gradients/scan/while/Beta/sample/random_gamma_1/RandomGamma_grad/Shape_1/Identity/Enter}}This is an internal bug, please file a bug report with instructions on how to reproduce the error.

During handling of the above exception, another exception occurred:

InternalError                             Traceback (most recent call last)
<ipython-input-1-6ad2e5bbd906> in <module>
     30 sess = tf.Session()
     31 sess.run(tf.global_variables_initializer())
---> 32 sess.run([loss, train_op], feed_dict={inputs: np.random.rand(3,2,1), targets: np.random.rand(3,2,1)})

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InternalError: Invalid loop structure: Mismatched parent frames for "scan/while/while_context": "gradients/scan/while/while_context" vs "". The node giving this error: node gradients/scan/while/Beta/sample/random_gamma_1/RandomGamma_grad/Shape_1/Identity/Enter (defined at <ipython-input-1-6ad2e5bbd906>:28) This is an internal bug, please file a bug report with instructions on how to reproduce the error.
```

**Comment by axch** [comment] 2019-05-09 22:08
@philipbecker Sorry for the delayed response, and thank you for finding this.  I confirmed that it also happens with 0.7 development version of TFP.

Based on the error message, it looks like something inside `tfp.Beta` managed to trigger an internal error in tf.scan, which would be a TF bug.  @jvdillon Do we have a process for redirecting bugs to TensorFlow proper?

**Comment by brianwa84** [comment] 2019-05-17 15:24
TFP distributions can broadcast, so (I think) you can get away with something like this:

```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions

inputs = tf.placeholder(tf.float32, (None, None, 1))
targets = tf.placeholder(tf.float32, (None, None, 1))

alpha = tf.layers.dense(inputs, 1, activation=tf.nn.softplus)
beta = tf.layers.dense(inputs, 1, activation=tf.nn.softplus)
beta_dist = tfd.Beta(alpha, beta)
sample = beta_dist.sample()
outputs = sample

predictions = tf.layers.dense(outputs, 1)
loss = tf.losses.mean_squared_error(predictions, targets)

optimizer = tf.train.GradientDescentOptimizer(1e-3)
train_op = optimizer.minimize(loss)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
feeds = {inputs: np.random.rand(3,2,1), targets: np.random.rand(3,2,1)}
for _ in range(100):
  print(sess.run([loss, train_op], feed_dict=feeds))
```

**Comment by srvasude** [comment] 2020-02-08 08:19
Closing this, because I believe Brian's fix should work. In TF2, this will be very much the same (with a tf.function on the relevant loss code, and avoiding use of Session's). Feel free to reopen if this is still an issue.

**Closed by srvasude** 2020-02-08 08:19 UTC
