### ISSUE TITLE
TypeError: Eager execution of tf.constant with unsupported shape

### ISSUE THREAD

**Issue by JimAva** [tensorflow/probability#379] opened 2019-04-23 20:59 UTC
I'm trying to modify the code from "Probabilistic_Layers_Regression.ipynb" for input_shape of 8 and output_shape of 8.  I get the following error from the sample code below.  Any ideas why?  Thanks
----**Error**------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-4b085f1fa672> in <module>()
     11                         dtype=x.dtype)[..., np.newaxis]),
     12         unconstrained_observation_noise_variance_initializer=(
---> 13             tf.constant_initializer(np.array(0.54).astype(x.dtype))),
     14     ),
     15 ])

TypeError: Eager execution of tf.constant with unsupported shape (value has 40 elements, shape is (1, 40, 8) with 320 elem

------**code**--------
num_inducing_points = 40
model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=[8], dtype=x.dtype),  #input shape 1
    tf.keras.layers.Dense(8, kernel_initializer='ones', use_bias=False),
    tfp.layers.VariationalGaussianProcess(
        num_inducing_points=num_inducing_points,
        kernel_provider=RBFKernelFn(dtype=x.dtype),
        event_shape=[1], #x.shape[1]],                                  
        inducing_index_points_initializer=tf.constant_initializer(
            np.linspace(*x_range, num=num_inducing_points,
                        dtype=x.dtype)[..., np.newaxis]),
        unconstrained_observation_noise_variance_initializer=(
            tf.constant_initializer(np.array(0.54).astype(x.dtype))),
    ),
])

**Comment by JimAva** [comment] 2019-04-24 20:02
I can't find any documentation on ' tfp.layers.VariationalGaussianProcess' for help.  Any advice is appreciated.

**Comment by axch** [comment] 2019-05-09 19:01
I was not able to reproduce the error from the posted code snippet.  If this is still a problem for you, could you give a complete running example that reproduces the error with as little code as possible?  A public colab (https://colab.sandbox.google.com/) is very easy for us to interact with.

Generically, adding `print(foo.shape)` all over the place is your friend for debugging shape errors.

**Comment by csuter** [comment] 2019-05-09 19:06
(I edited Alexey's comment to point to the non-Google-internal site name, colab.research instead of colab.sandbox -- that latter redirects anyway, but hopefully this will prevent any confusion)

**Comment by srvasude** [comment] 2020-02-08 02:19
Closing this. Feel free to reopen if this is a recurring issue.

**Closed by srvasude** 2020-02-08 02:19 UTC

**Comment by dawranadeep** [comment] 2020-10-20 01:09
Did you find anything?

**Comment by sharm636** [comment] 2021-09-01 22:14
Facing the same issue when the number of input and output nodes to the VariationalGaussianProcess layer is anything other than 1.

**Comment by Fakhfaakh** [comment] 2021-10-14 11:27
Same issue, any help?
