### ISSUE TITLE
Simulating maximum likelihood ratio test statistic

### ISSUE THREAD

**Issue by bjfar** [tensorflow/probability#383] opened 2019-04-26 08:16 UTC
My apologies if this is the wrong place to ask this, but I am trying to figure out how to simulate the distribution of likelihood ratio test statistics with tensorflow/probability. I am new to tensorflow entirely, so I also apologise if this is covered in tutorials somewhere, but I couldn't find one covering this.

Anyway here is my attempt:

    import tensorflow as tf
    import tensorflow_probability as tfp
    from tensorflow_probability import distributions as tfd
    import seaborn as sns
    import numpy as np
    import matplotlib.pyplot as plt

    tf.compat.v1.disable_eager_execution()

    # Bunch of independent Poisson distributions that we want to combine
    poises = [tfp.distributions.Poisson(rate = 13) for i in range(5)]
    poises0 = [tfp.distributions.Poisson(rate = 10) for i in range(5)]

    # Construct joint distributions
    joint = tfd.JointDistributionSequential(poises)
    joint0 = tfd.JointDistributionSequential(poises0)

    N = int(1e3) # Can be done!
    samples = joint.sample(N)
    samples0 = joint0.sample(N)

    # Now we need the same distributions but with floating parameters
    mus = [tf.Variable(np.random.randn(), name='mu{0}'.format(i)) for i in range(5)]
    poises_free = [tfp.distributions.Poisson(rate = mus[i]) for i in range(5)]
    joint_free = tfd.JointDistributionSequential(poises0)

    # Construct (half of) test statistic
    q_free = -2*(joint_free.log_prob(samples))

    # Minimise
    opt = tf.optimizers.SGD(0.1).minimize(q_free,var_list=mus)

    sess = tf.compat.v1.Session()
    sess.run(tf.global_variables_initializer())
    q = sess.run(opt)
    print(q)

    # do plotting of test statistic...

The basic idea is to construct the joint distribution (five independent Poisson distributions in this case), sample some pseudodata from them, maximise the joint likelihood (treating the five Poisson means as our five model parameters) for each pseudo-observation, and then plot the distribution of the maximum likelihood ratio test statistic (should be close to chi-squared with 5 DOF in this case).

However, running the above code I get this error:

    TypeError: 'Tensor' object is not callable

I guess it is complaining because it doesn't know that it is supposed to perform the minimisation for each pseudo-data realisation. How should I get it to do this? Using a loop feels like it would be dumb and slow and not the way TensorFlow is designed to work.

**Comment by bjfar** [comment] 2019-04-26 08:20
On a side note, none of the "edit" buttons for this post work. I would delete the lines where I generate second sets of pseudodata under different parameters, those are not relevant to the question, but it seems that I cannot.

**Comment by csuter** [comment] 2019-04-26 08:27
I think the issue is just that the new tf optimizers API takes a callable, where the old one took a `Tensor`. The callable should compute and return the loss value you need to optimize. Since the gradient computation needs to "see" the whole computational flow from `Variable`s to loss, you'll need to wrap up a few lines of your code in the callable. Something like

```
mus = [tf.Variable(np.random.randn(), name='mu{0}'.format(i)) for i in range(5)]

def loss():
  poises_free = [tfp.distributions.Poisson(rate = mus[i]) for i in range(5)]
  joint_free = tfd.JointDistributionSequential(poises0)

  # Construct (half of) test statistic
  return -2*(joint_free.log_prob(samples))

# Minimise
opt = tf.optimizers.SGD(0.1).minimize(loss, var_list=mus)
```

I'm not 100% sure that code will work as written because it seems to be mixing TF1 and TF2 idioms, but that's the spirit of the TF2 style, anyway. Give it a try and see if it gets you up and running.

Also: while your adoption of the *very* new JointDistributionSequential is admirable, there's a more efficient way to express what you're doing here. When you have what we call a "batch" of Distributions from the same family, you can use `tfd.Independent` to combine them into a single joint distribution directly:

```
joint = tfp.distributions.Independent(
    tfp.distributions.Poisson(rate = [13] * 5)),
    reinterpreted_batch_ndims=1)
```

This has the advantage of vectorizing all computations, whereas the JointDistribution you wrote will (essentially) use for loops under the hood.

**Comment by bjfar** [comment] 2019-04-26 09:32
Ahh excellent, thanks, I think that works. However I am now not sure how to get the results of the optimisation. I need to compute the maximum likelihood ratio for each pseudodata realisation. The documentation seems to just say that the parameters are optimised following the optimisation operation, so I guess I need to construct another computation node which somehow depends on the results of each optimisation? How would that be done?

**Comment by axch** [comment] 2019-05-09 19:46
Your nans are probably coming from initializing the Poissons with negative rates.

It's probably also a good idea to make the learning rate smaller than 0.1: with a rate that large, it's not hard for an optimizer to walk off into a parameter regime where numerical problems dominate (e.g., accidentally making a rate negative, or so large that the gradient explodes, etc).

In this particular example, as @csuter said, you're better off using `Independent` rather than `JointDistribution` -- the implementation is substantially more efficient for just lumping together a bunch of distributions in the same family.

Re: 5 instead of 1000 parameters: The code I'm reading only defines 5 Variables, each of scalar shape, and fits those 5 parameters to a 1000x5 set of Poisson draws.  (Actually, to really do that, there should be a reduce_sum in the loss, which may be implicitly supplied by the optimizer itself.)  Did you mean to define and fit a batch of 1000 rates?  Doing 50 samples each, for a 50x1000 data set, might look like this:

```
data = 4 * tf.ones(shape=[50, 1000])
mus = tf.compat.v2.Variable(np.ones(shape=1000), dtype=tf.float32)
def loss():
  poissons = tfp.distributions.Independent(
    tfp.distributions.Poisson(rate = mus), reinterpreted_batch_ndims=1)
  return -1 * tf.reduce_sum(poissons.log_prob(data), axis=0)
```

Finally, in TF2, optimizer.minimize only runs one step (holdover from graph-building days), so to get it to converge, you want to invoke it multiple times.

**Comment by bjfar** [comment] 2019-05-10 08:02
Thanks, yeah, that is pretty much what I ended up with (I made a StackOverflow question, and though no-one helped me there the solution is posted https://stackoverflow.com/a/55923875/1447953).

**Comment by axch** [comment] 2019-05-10 16:54
OK, looks like we can close this issue, then.

**Closed by axch** 2019-05-10 16:54 UTC
