### ISSUE TITLE
Calling cdf() with multiple values of x using a Poisson distribution defined by multiple values of rate

### ISSUE THREAD

**Issue by echan5** [tensorflow/probability#1145] opened 2020-10-29 00:18 UTC
Hi,

I have a use case where I'd like to define an instance of `tfp.distributions.Poisson` using a `rate` of length > 1 (due to batching), and then subsequently call its `cdf()` passing in `x` of length > 1.

Currently the following works for a single value of rate and multiple values of x:
```
import  tensorflow_probability as tfp
rate = 5
x = [1, 5, 17]
p1 = tfp.distributions.Poisson(rate=rate)
p1.cdf(x)
# returns  <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.04042768, 0.6159606 , 0.9999946 ], dtype=float32)>
```

The following also works for multiple values of rate and a single value of x:
```
rate = [5, 10]
x = 1
p1 = tfp.distributions.Poisson(rate=rate)
p1.cdf(x)
# returns <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.04042768, 0.0004994 ], dtype=float32)>
```

However, the following for multiple values of rate and multiple value of x does not work:
```
rate = [5, 10]
x = [1, 5, 17]
p1 = tfp.distributions.Poisson(rate=rate)
p1.cdf(x)
# InvalidArgumentError: Incompatible shapes: [3] vs. [2] [Op:Igammac]
```

I believe the fix would be to add a reshape like the below, which works:
```
import tensorflow_probability as tfp
import tensorflow as tf

class CustomPoisson(tfp.distributions.Poisson):
    def _cdf(self, x):
        safe_x = tf.maximum(x if self.interpolate_nondiscrete else tf.floor(x), 0.)
        rate = self._rate_parameter_no_checks()
        rate = tf.reshape(rate, (-1, 1))
        cdf = tf.math.igammac(1. + safe_x, rate)
        return tf.where(x < 0., tf.zeros_like(cdf), cdf)

rate = [5, 10]
x = [1, 5, 17]

p2 = CustomPoisson(rate=rate)
p2.cdf(x)
# returns <tf.Tensor: shape=(2, 3), dtype=float32, numpy=array([[4.0427685e-02, 6.1596060e-01, 9.9999458e-01],
       [4.9939926e-04, 6.7085974e-02, 9.8572236e-01]], dtype=float32)>
```

Would this be a reasonable change? If so, I'll put in a PR but I wanted to check first. I was looking at Poisson specifically but I'm not sure if the same applies for other distributions.

Please let me know what you think! Thanks

**Comment by brianwa84** [comment] 2020-10-29 01:37
This is the intended behavior. If you look at p1.batch_shape (will be (3,))
and p1.event_shape (will be ()), the x you pass into cdf needs to be
broadcast compatible with the concatenation of (3,) and (), i.e. (3,).

The shape (2,) is not broadcast compatible, but the shape (2, 1) is.

In general, you could even pass in higher order rate tensors, shaped say
(3, 4, 1, 5) and x shaped (4, 6, 1) and get out cdfs with shape (3, 4, 6,
5). So the reshape strategy won't generalize sufficiently.

**Comment by brianwa84** [comment] 2020-10-29 01:42
Perhaps this is a good place to plug batch slicing. You could also write

p1[..., tf.newaxis].cdf(x)

The slice adds a new batch dim of size 1 at the end, so you get a dist with
batch shape (3, 1), which is broadcast compatible with (2,) to yield a cdf
shaped (3, 2).

You can do fancier things too, like taking every other element [::2],
grabbing the last in a dim [-1], etc.

**Comment by csuter** [comment] 2020-10-30 16:21
Hi @echan5, this notebook might provide some helpful context on Distribution shapes: https://www.tensorflow.org/probability/examples/Understanding_TensorFlow_Distributions_Shapes

There was also a very nice blog post by @ericmjl here: https://ericmjl.github.io/blog/2019/5/29/reasoning-about-shapes-and-probability-distributions/. In particular, the section on broadcasting may be illuminating for the case you raise.

I'll close this as WAI, but please do feel free to follow up with any questions.

**Closed by csuter** 2020-10-30 16:21 UTC

**Comment by echan5** [comment] 2020-11-03 19:21
@brianwa84 @csuter A little belated in my response to this, but I wanted to say thank you for pointing to an alternate solution (didn't know about tf/np newaxis), and the notebook and blog post also provided more clarity and were very helpful for someone still trying to get a better handle of shapes and manipulating shape. Thanks!
